package com.example.pdfreports;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class PdfReportGenerator {

    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    private static final int PAGE_WIDTH = 595;
    private static final int PAGE_HEIGHT = 842;
    private static final int LEFT_MARGIN = 48;
    private static final int TOP_MARGIN = 790;
    private static final int BOTTOM_MARGIN = 54;
    private static final int LINE_HEIGHT = 22;
    private static final int TABLE_TOP_MARGIN = 650;
    private static final int TABLE_ROW_HEIGHT = 24;
    private static final int TITLE_X = 64;
    private static final int TABLE_X = 48;
    private static final int TABLE_WIDTH = 499;

    public byte[] generateMovieReport(MovieReportParams params) {
        List<String> pages = createReportPages(params);
        return buildPdf(pages);
    }

    private List<String> createReportPages(MovieReportParams params) {
        List<MovieReportItem> movies = params.movies() == null ? List.of() : params.movies();
        String title = blankToDefault(params.title(), "MovieRate report");
        String generatedBy = blankToDefault(params.generatedBy(), "MovieRate");
        String generatedAt = params.generatedAt() == null ? "" : params.generatedAt().format(DATE_FORMATTER);

        List<String> pages = new ArrayList<>();
        int rowsPerPage = (TABLE_TOP_MARGIN - BOTTOM_MARGIN) / TABLE_ROW_HEIGHT;
        int pageCount = Math.max(1, (int) Math.ceil(movies.size() / (double) rowsPerPage));

        for (int pageIndex = 0; pageIndex < pageCount; pageIndex++) {
            StringBuilder page = new StringBuilder();
            renderHeader(page, title, generatedBy, generatedAt, movies, pageIndex + 1, pageCount);
            renderTableHeader(page);

            int first = pageIndex * rowsPerPage;
            int last = Math.min(first + rowsPerPage, movies.size());
            if (movies.isEmpty()) {
                appendText(page, "No movies were provided for this report.", TABLE_X + 16, TABLE_TOP_MARGIN - 42, 12, "/F2");
            } else {
                for (int i = first; i < last; i++) {
                    renderMovieRow(page, movies.get(i), i + 1, TABLE_TOP_MARGIN - 34 - ((i - first) * TABLE_ROW_HEIGHT));
                }
            }
            pages.add(page.toString());
        }

        return pages;
    }

    private void renderHeader(StringBuilder page, String title, String generatedBy, String generatedAt,
                              List<MovieReportItem> movies, int pageNumber, int pageCount) {
        appendRect(page, 0, 760, PAGE_WIDTH, 82, "0.08 0.12 0.18", true);
        appendRect(page, 48, 730, TABLE_WIDTH, 1, "0.82 0.86 0.92", true);
        appendText(page, "MovieRate", TITLE_X, 812, 12, "/F2", "0.82 0.86 0.92");
        appendText(page, title, TITLE_X, 786, 22, "/F1", "1 1 1");
        appendText(page, "Generated by: " + generatedBy, TITLE_X, 746, 10, "/F2", "0.25 0.29 0.35");
        appendText(page, "Generated at: " + blankToDefault(generatedAt, "-"), 330, 746, 10, "/F2", "0.25 0.29 0.35");

        appendSummaryCard(page, "Movies", String.valueOf(movies.size()), 48, 680);
        appendSummaryCard(page, "Avg rating", averageRating(movies), 216, 680);
        appendSummaryCard(page, "Page", pageNumber + " / " + pageCount, 384, 680);
    }

    private void appendSummaryCard(StringBuilder page, String label, String value, int x, int y) {
        appendRect(page, x, y, 140, 54, "0.94 0.96 0.98", true);
        appendRect(page, x, y, 140, 54, "0.78 0.83 0.90", false);
        appendText(page, label, x + 14, y + 33, 9, "/F2", "0.36 0.40 0.46");
        appendText(page, value, x + 14, y + 13, 18, "/F1", "0.08 0.12 0.18");
    }

    private void renderTableHeader(StringBuilder page) {
        appendRect(page, TABLE_X, TABLE_TOP_MARGIN - 8, TABLE_WIDTH, 28, "0.12 0.16 0.22", true);
        appendText(page, "#", TABLE_X + 12, TABLE_TOP_MARGIN, 10, "/F1", "1 1 1");
        appendText(page, "Title", TABLE_X + 42, TABLE_TOP_MARGIN, 10, "/F1", "1 1 1");
        appendText(page, "Year", TABLE_X + 320, TABLE_TOP_MARGIN, 10, "/F1", "1 1 1");
        appendText(page, "Type", TABLE_X + 374, TABLE_TOP_MARGIN, 10, "/F1", "1 1 1");
        appendText(page, "Rating", TABLE_X + 450, TABLE_TOP_MARGIN, 10, "/F1", "1 1 1");
    }

    private void renderMovieRow(StringBuilder page, MovieReportItem movie, int index, int y) {
        if (index % 2 == 0) {
            appendRect(page, TABLE_X, y - 7, TABLE_WIDTH, TABLE_ROW_HEIGHT, "0.97 0.98 0.99", true);
        }
        appendRect(page, TABLE_X, y - 7, TABLE_WIDTH, 1, "0.88 0.91 0.95", true);
        appendText(page, String.valueOf(index), TABLE_X + 12, y, 9, "/F2", "0.24 0.28 0.34");
        appendText(page, truncate(blankToDefault(movie.title(), "Untitled"), 42), TABLE_X + 42, y, 9, "/F2", "0.08 0.12 0.18");
        appendText(page, valueOrDash(movie.releaseYear()), TABLE_X + 320, y, 9, "/F2", "0.24 0.28 0.34");
        appendText(page, truncate(blankToDefault(movie.type(), "-"), 10), TABLE_X + 374, y, 9, "/F2", "0.24 0.28 0.34");
        appendText(page, formatRating(movie.averageRating()), TABLE_X + 450, y, 9, "/F1", "0.08 0.12 0.18");
    }

    private void appendText(StringBuilder page, String text, int x, int y, int fontSize, String font) {
        appendText(page, text, x, y, fontSize, font, "0 0 0");
    }

    private void appendText(StringBuilder page, String text, int x, int y, int fontSize, String font, String color) {
        page.append(color).append(" rg BT ")
                .append(font).append(" ").append(fontSize).append(" Tf ")
                .append(x).append(" ").append(y)
                .append(" Td (").append(escapePdfText(normalizeText(text))).append(") Tj ET\n");
    }

    private void appendRect(StringBuilder page, int x, int y, int width, int height, String color, boolean fill) {
        page.append(color).append(fill ? " rg " : " RG ")
                .append(x).append(" ").append(y).append(" ").append(width).append(" ").append(height)
                .append(" re ").append(fill ? "f" : "S").append("\n");
    }

    private byte[] buildPdf(List<String> pageContents) {
        List<byte[]> objects = new ArrayList<>();
        objects.add("<< /Type /Catalog /Pages 2 0 R >>".getBytes(StandardCharsets.ISO_8859_1));
        objects.add(buildPagesObject(pageContents.size()).getBytes(StandardCharsets.ISO_8859_1));
        objects.add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>".getBytes(StandardCharsets.ISO_8859_1));
        objects.add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>".getBytes(StandardCharsets.ISO_8859_1));

        int firstPageObject = 5;
        int firstContentObject = firstPageObject + pageContents.size();

        for (int i = 0; i < pageContents.size(); i++) {
            int contentObjectNumber = firstContentObject + i;
            objects.add(("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 " + PAGE_WIDTH + " " + PAGE_HEIGHT
                    + "] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents "
                    + contentObjectNumber + " 0 R >>").getBytes(StandardCharsets.ISO_8859_1));
        }

        for (String pageContent : pageContents) {
            byte[] stream = pageContent.getBytes(StandardCharsets.ISO_8859_1);
            objects.add(("<< /Length " + stream.length + " >>\nstream\n"
                    + pageContent + "endstream").getBytes(StandardCharsets.ISO_8859_1));
        }

        return writePdf(objects);
    }

    private String buildPagesObject(int pageCount) {
        StringBuilder kids = new StringBuilder();
        for (int i = 0; i < pageCount; i++) {
            kids.append(5 + i).append(" 0 R ");
        }
        return "<< /Type /Pages /Kids [" + kids + "] /Count " + pageCount + " >>";
    }

    private byte[] writePdf(List<byte[]> objects) {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        List<Integer> offsets = new ArrayList<>();
        write(output, "%PDF-1.4\n");

        for (int i = 0; i < objects.size(); i++) {
            offsets.add(output.size());
            write(output, (i + 1) + " 0 obj\n");
            output.writeBytes(objects.get(i));
            write(output, "\nendobj\n");
        }

        int xrefOffset = output.size();
        write(output, "xref\n0 " + (objects.size() + 1) + "\n");
        write(output, "0000000000 65535 f \n");
        for (Integer offset : offsets) {
            write(output, String.format(Locale.ROOT, "%010d 00000 n \n", offset));
        }
        write(output, "trailer\n<< /Size " + (objects.size() + 1) + " /Root 1 0 R >>\n");
        write(output, "startxref\n" + xrefOffset + "\n%%EOF");

        return output.toByteArray();
    }

    private void write(ByteArrayOutputStream output, String text) {
        output.writeBytes(text.getBytes(StandardCharsets.ISO_8859_1));
    }

    private String blankToDefault(String value, String defaultValue) {
        return value == null || value.isBlank() ? defaultValue : value;
    }

    private String valueOrDash(Integer value) {
        return value == null ? "-" : value.toString();
    }

    private String formatRating(Double rating) {
        return rating == null ? "-" : String.format(Locale.ROOT, "%.1f", rating);
    }

    private String averageRating(List<MovieReportItem> movies) {
        double average = movies.stream()
                .filter(movie -> movie.averageRating() != null)
                .mapToDouble(MovieReportItem::averageRating)
                .average()
                .orElse(0);
        return String.format(Locale.ROOT, "%.1f", average);
    }

    private String truncate(String value, int maxLength) {
        return value.length() <= maxLength ? value : value.substring(0, maxLength - 3) + "...";
    }

    private String normalizeText(String text) {
        return text == null ? "" : text.replaceAll("[^\\x20-\\x7E]", "?");
    }

    private String escapePdfText(String text) {
        return text.replace("\\", "\\\\")
                .replace("(", "\\(")
                .replace(")", "\\)");
    }
}
