spring.application.name=MovieRateBackend

# Baza Danych PostgreSQL (domyślne porty lokalne)
spring.datasource.url=jdbc:postgresql://localhost:5432/movierate
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tryb inicjalizacji skryptów SQL (uruchomi schema.sql przy starcie pomijając ewentualne konflikty)
spring.sql.init.mode=always

# Seed danych startowych
app.seed.enabled=true
